// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  featured_articles: dynamic(() => import("./FeaturedArticles")),
  hero_section: dynamic(() => import("./HeroSection")),
};
